### ISSUE TITLE
Create initial assets for construction kit

### ISSUE THREAD

**Issue by dkammer** [visualengineers/cobro-data#1]
We need the graphics for the building blocks of the construction kit as vector and pixel format. (put inside _assets folder).

**Comment by rsiedler-designs** [comment]
Graphics as vector (.svg) and pixel format (.png) are uploaded.

**Comment by dkammer** [comment]
- [ ] Check for transparency in PNG exports
- [ ] Export with 300dpi resolution
- [ ] Check filenames for consistency
- [ ] Add Illustrator file as source for the icons into "_assets" folder

**Comment by rsiedler-designs** [comment]
complete
