### ISSUE TITLE
Adapt schema for pattern.json to include link to assets

### ISSUE THREAD

**Issue by dkammer** [visualengineers/cobro-data#17]
There might be an abstracted graphic for a pattern in the assets folder -- add a boolean to schema if this exists.

**Comment by tobiasrother** [comment]
In the Commit: 2366cecc39800c858bdc31187d1361902bf62e1c I added the graphic boolean. I decided that it is a not required property.

**Comment by dkammer** [comment]
> In the Commit: [2366cec](https://github.com/visualengineers/cobro-data/commit/2366cecc39800c858bdc31187d1361902bf62e1c) I added the graphic boolean. I decided that it is a not required property.

Agreed!
