### ISSUE TITLE
Changes to the icon.ai

### ISSUE THREAD

**Issue by tobiasrother** [visualengineers/cobro-data#19]
- [x] Rename Names in WHY category (Summarize, Compare, Identify)
- [x] Delete category Name "Search Task" in WHY category
- [x] a new order under HOW/ Visual Element/ Form
- [x] Rearrange category Dimension and Grid 
- [x] Rename catefory Dimension to Spatiality
- [x] Rearrange category Spatiality to one Group (Dimensionality) and to Elements (2 Dimensional/ 3 Dimensional
- [x] a new order under HOW/ Interaction/ View Transformation

**Comment by rsiedler-designs** [comment]
Done. New version would be uploaded.
