### ISSUE TITLE
IDs for Construction Plans and Pattern.

### ISSUE THREAD

**Issue by tobiasrother** [visualengineers/cobro-data#6]
The "construction plans" are numbered in the form "cpxxx" starting with "cp001". Should the "patterns" be numbered in the same way? Or is another numbering like "pattern_X" starting with "pattern_A" up to "pattern_ZZ" more appropriate to make a clear difference.

**Comment by dkammer** [comment]
Good question. Each pattern should be a general solution and should get a unique "description" or "name. Consider the example:

![Bildschirmfoto 2019-05-13 um 11 27 44](https://user-images.githubusercontent.com/26138444/57611033-42dcd100-7572-11e9-976b-81789343cf55.png)

So we might do it similar to the projects and not use anonymous IDs but concrete (short) names such as: "resultlistimagetext.json" or "mapbasedsearch.json" to store a pattern?

I'm interested in @mandyTUD opinion as well.

**Comment by mandyTUD** [comment]
The IDs are important to store cross-references to other patterns. Maybe the combination of the name and an ID would fit, such as  "pAAA_resultlistwithimagetext" and "pAAB_mapbasedsearch" (or numbers instead of letters)

**Comment by dkammer** [comment]
> The IDs are important to store cross-references to other patterns. Maybe the combination of the name and an ID would fit, such as "pAAA_resultlistwithimagetext" and "pAAB_mapbasedsearch" (or numbers instead of letters)

But the patterns themselves are unique and should be re-used. The ID is maybe only important when describing the references in the construction plan if one pattern is found multiple times in a construction plan? Maybe we can add the specific IDs there @tobiasrother

**Comment by tobiasrother** [comment]
In the construction plan is the attribute "pattern" which contains all patterns used in the plan, these could be used to determine "edges" and "references". 
So you could enter "pattern_A" twice in the attribute "pattern". Once at position 0 in the array and at position 1, this index is then used by the properties "edges" and "references". 
So far they still use the ID´s of the patterns themselves.

**Comment by dkammer** [comment]
> this index is then used by the properties "edges" and "references"

You suggest to change the type of "source" and "target" inside an edge to integer, which is then the index of the pattern array? I think this could work, but the description of the properties should be clear. Reading the edges also becomes a little bit more difficult for a human, but I think that's ok.

**Comment by tobiasrother** [comment]
> You suggest to change the type of "source" and "target" inside an edge to integer, which is then the index of the pattern array?

Yes, that's the idea and also for the "source" and "target" inside the "reference" attribute.
